### ISSUE TITLE
Where is av_test.json file?

### ISSUE THREAD

**Issue by kylemin** [EGO4D/audio-visual#3]
How can I download the file? Everything related to this file is commented out. Why so?

**Comment by miguelmartin75** [comment]
Test files will be released soon. They will not contain annotations, due to the challenge.

**Comment by kylemin** [comment]
What kind of annotations will be included in the av_test.json? Will tracks part of it? Or only the clip_ids will be included?

**Comment by jachymuv** [comment]
Aren't you getting the av_test_unannotated.json when downloading annotations via the Ego4D CLI tool? It was made available on Apr 6th. Please try to download the annotations one more time and let us know should you not get this file.

**Comment by kylemin** [comment]
I see, I just downloaded the test files. Thanks!
