### ISSUE TITLE
Question on README

### ISSUE THREAD

**Issue by kylemin** [EGO4D/audio-visual#4]
What is the code's root directory (ego4d_av_diaraization) that is mentioned in the README as below? Is it necessary to move something to '~/.cache/torch/hub/'? Is there any workaround?

`
Then, untar the file in the code's root directory (ego4d_av_diaraization). The directory should be named as 'models'. Inside the models directory, expand the snakers4_silero-vad_master.zip and then move the directory of 'snakers4_silero-vad_master' to '~/.cache/torch/hub/'.
`

**Comment by seattlesunshine** [comment]
The root is the "audio-visual". I will update the readme. You should put all the models in the "models" directory under audio-visual. Yes, it is necessary to move the snakers4_silero-vad_master in the models subdirectory to ~/.cache/torch/hub/.
