### ISSUE TITLE
Model for people detection

### ISSUE THREAD

**Issue by sanjayss34** [EGO4D/audio-visual#7]
Hi, I believe we need a darknet model to do the people detection. Could you please release these model weights? Or provide instructions on how we can train a model similar to the one you used? Thank you!

**Comment by seattlesunshine** [comment]
The darknet model used in the baseline is included. You need to run a script to download it (with other models) from S3. Check the ego4d ReadMes. Let me know if you cannot find the corresponding command.

**Comment by seattlesunshine** [comment]
Check the README in diariziaion/audio-visual. There is a python command to download all the models.
