### ISSUE TITLE
spk2utt: No such file or directory

### ISSUE THREAD

**Issue by Echo0125** [EGO4D/audio-visual#9]
Hi, I follow the steps from the audio-only Readme, but when I run **vad_kaldi/run_vad.sh**, I get **spk2utt: No such file or directory**. I don't know how to solve the problem...

**Comment by jachymuv** [comment]
Hi,
 **spk2utt** is a text file that should have been created in the folder specified by the DATA_DIR variable in the **vad_kaldi/run_vad.sh** script. Have you edited all the variables in that script to correspond with your local directory setup? Have you checked that your Kaldi installation works ( https://kaldi-asr.org/doc/build_setup.html ) ?

**Comment by Echo0125** [comment]
> Hi, **spk2utt** is a text file that should have been created in the folder specified by the DATA_DIR variable in the **vad_kaldi/run_vad.sh** script. Have you edited all the variables in that script to correspond with your local directory setup? Have you checked that your Kaldi installation works ( https://kaldi-asr.org/doc/build_setup.html ) ?

I think my Kaldi installation works. I run /kaldi/egs/yesno/s5/run.sh and the output is normal. Besides, in **vad_kaldi/run_vad.sh** I don't find any code to create **spk2utt**.

**Comment by Echo0125** [comment]
I have solved the problem. In **vad_kaldi/run_vad.sh**, I should set DataRoot absolute path, but I set it to a relative path. Thanks!
